language: python
python:
  - "3.9"
git:
  clone: false
install:
  - git clone --branch=$TRAVIS_BRANCH https://github.com/$TRAVIS_REPO_SLUG.git $TRAVIS_REPO_SLUG
  - cd $TRAVIS_REPO_SLUG
  - pip install -r requirements.txt
script:
  - coverage run -m unittest
after_success:
  coveralls